import React from 'react';
import {
    Box, Button, Chip, Dialog, DialogContent, DialogTitle,
    Divider, IconButton, Stack, Typography
} from '@mui/material';
import CloseRoundedIcon from '@mui/icons-material/CloseRounded';
import DownloadRoundedIcon from '@mui/icons-material/DownloadRounded';
import AutoAwesomeRoundedIcon from '@mui/icons-material/AutoAwesomeRounded';
import { tokens } from '../theme';

function Section({ title, items, renderItem }) {
    if (!items?.length) return null;

    return (
        <Box>
            <Typography variant="h6" sx={{ mb: 1 }}>{title}</Typography>
            <Stack component="ul" spacing={0.75} sx={{ pl: 2.5, m: 0 }}>
                {items.map((item, i) => (
                    <Typography key={i} component="li" variant="body2" sx={{ color: tokens.text.secondary }}>
                        {renderItem ? renderItem(item) : item}
                    </Typography>
                ))}
            </Stack>
        </Box>
    );
}

export default function SummaryDialog({ open, onClose, summary, onDownload }) {
    if (!summary) return null;

    const nothingExtracted =
        !summary.key_points?.length && !summary.decisions?.length && !summary.action_items?.length;

    return (
        <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
            <DialogTitle sx={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 2 }}>
                <Stack direction="row" spacing={1.25} alignItems="center">
                    <AutoAwesomeRoundedIcon sx={{ color: tokens.accent.light }} />
                    <Box>
                        <Typography variant="h5">{summary.title}</Typography>
                        <Typography variant="caption" sx={{ color: tokens.text.tertiary }}>
                            Generated by Claude from the meeting transcript
                        </Typography>
                    </Box>
                </Stack>
                <IconButton onClick={onClose} size="small" aria-label="Close">
                    <CloseRoundedIcon fontSize="small" />
                </IconButton>
            </DialogTitle>

            <DialogContent>
                {summary.truncated && (
                    <Chip
                        size="small"
                        label="Long meeting — summarised from the latter part of the transcript"
                        sx={{ mb: 2, bgcolor: "rgba(245,165,36,0.12)", color: tokens.warning.main }}
                    />
                )}

                <Stack spacing={2.5}>
                    <Typography variant="body2" sx={{ color: tokens.text.secondary }}>
                        {summary.summary}
                    </Typography>

                    <Divider />

                    <Section title="Key points" items={summary.key_points} />
                    <Section title="Decisions" items={summary.decisions} />
                    <Section
                        title="Action items"
                        items={summary.action_items}
                        renderItem={(item) => (
                            <>
                                {item.task}
                                <Box component="span" sx={{ color: tokens.text.tertiary }}> — {item.owner}</Box>
                            </>
                        )}
                    />

                    {nothingExtracted && (
                        <Typography variant="body2" sx={{ color: tokens.text.tertiary }}>
                            No decisions or action items were identified in this conversation.
                        </Typography>
                    )}

                    <Button
                        variant="outlined"
                        startIcon={<DownloadRoundedIcon fontSize="small" />}
                        onClick={onDownload}
                        sx={{ alignSelf: "flex-start" }}
                    >
                        Download as Markdown
                    </Button>

                    <Typography variant="caption" sx={{ color: tokens.text.tertiary }}>
                        AI-generated from imperfect speech recognition — check anything important
                        against what was actually said.
                    </Typography>
                </Stack>
            </DialogContent>
        </Dialog>
    );
}
